In [35]:
import numpy as np
import pandas as pd

df_iris = pd.read_csv(u'data/iris.txt', sep=' ')


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

feature_sl = np.matrix(df_iris.sl[:]).T
feature_sw = np.matrix(df_iris.sw[:]).T
feature_pl = np.matrix(df_iris.pl[:]).T
feature_pw = np.matrix(df_iris.pw[:]).T

iris_type = np.matrix(df_iris.c[:]).T

X = np.vstack([df_iris.sl[i], df_iris.sw[i], df_iris.pl[i], df_iris.pw[i]] for i in range(len(iris_type)))

w = np.mat('[0;0;0;0]')

mark_1 = np.vstack(1 if iris_type[i] == 1 else 0 for i in range(len(iris_type)))
mark_2 = np.vstack(1 if iris_type[i] == 2 else 0 for i in range(len(iris_type)))
mark_3 = np.vstack(1 if iris_type[i] == 3 else 0 for i in range(len(iris_type)))

eta = 0.001
for i in range(10000):
    pr = sigmoid(X * w)
    w = w + eta * X.T * (mark_1 - pr)

print("w1")
print(w)

eta = 0.001
for i in range(10000):
    pr = sigmoid(X * w)
    w = w + eta * X.T * (mark_2 - pr)

print("\n")
print("w2")    
print(w)

eta = 0.001
for i in range(10000):
    pr = sigmoid(X * w)
    w = w + eta * X.T * (mark_3 - pr)
    
print("\n")
print("w3")   
print(w)

w1
[[ 0.93933138]
 [ 3.02491508]
 [-4.64943993]
 [-2.17020562]]




w2
[[ 0.73278841]
 [-1.87846093]
 [ 1.04729739]
 [-2.84414427]]




w3
[[-4.88182804]
 [-4.94948557]
 [ 6.50110094]
 [ 7.7099585 ]]
