In [3]:
%matplotlib inline
import numpy as np
import pandas as pd

In [4]:
class IrisModel(object):

    def __init__(self, file_name, seperator=' '):
        data = pd.read_csv(u'data/{0}'.format(file_name), sep=seperator)

        feature1 = np.matrix(data.sl[0:]).T
        feature2 = np.matrix(data.sw[0:]).T
        feature3 = np.matrix(data.pl[0:]).T
        feature4 = np.matrix(data.pw[0:]).T

        self.X = np.hstack((feature1, feature2, feature3, feature4))
        self.c = np.matrix(data.c[0:]).T

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def classify(self, category, iteration_count=10000, eta=0.001):
        y = self.c.copy()
        w = np.matrix([1,1,1,1]).T

        item_count = len(y)
        for i in range(item_count):
            y[i,0] = 1 if y[i,0] == category else 0

        for i in range(iteration_count):
            pr = self.sigmoid(self.X * w)
            w = w + eta * self.X.T * (y - pr)

        return w

In [5]:
model = IrisModel('iris.txt');

In [11]:
print('# Classify 1 versus 2,3')
w1 = model.classify(1)
print(w1)

# Classify 1 versus 2,3
[[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]


In [10]:
print('# Classify 2 versus 1,3')
w2 = model.classify(2)
print(w2)

# Classify 2 versus 1,3
[[ 0.73300616]
 [-1.87866542]
 [ 1.04693053]
 [-2.84352623]]


In [12]:
print('# Classify 3 versus 1,2')
w3 = model.classify(3)
print(w3)

# Classify 3 versus 1,2
[[-4.80685745]
 [-4.96911165]
 [ 6.35877022]
 [ 7.88567013]]
