In [15]:
import numpy as np
import pandas as pd

df_iris = pd.read_csv(u'data/iris.txt', sep=' ')


eta = 0.001

# given iris type matrix
iris_type = np.matrix(df_iris.c[:]).T

# classify iris types. 1 for given type, 0 otherwise
mark_1 = np.vstack(1 if iris_type[i] == 1 else 0 for i in range(len(iris_type)))
mark_2 = np.vstack(1 if iris_type[i] == 2 else 0 for i in range(len(iris_type)))
mark_3 = np.vstack(1 if iris_type[i] == 3 else 0 for i in range(len(iris_type)))

# feature matrix
X = np.vstack([df_iris.sl[i], df_iris.sw[i], df_iris.pl[i], df_iris.pw[i]] for i in range(len(iris_type)))


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def find_w(logic_matrix, iris_type):
    # initial w
    w = np.mat('[0;0;0;0]')
    for i in range(10000):
        pr = sigmoid(X * w)
        w = w + eta * X.T * (logic_matrix - pr)

    print("*** w for type-" + iris_type + " ***")
    print(w)
    print("\n\n----------\n")

find_w(mark_1, "1")
find_w(mark_2, "2")
find_w(mark_3, "3")


*** w for type-1 ***
[[ 0.93933138]
 [ 3.02491508]
 [-4.64943993]
 [-2.17020562]]


----------

*** w for type-2 ***


[[ 0.73282994]
 [-1.87849993]
 [ 1.04722742]
 [-2.84402639]]


----------

*** w for type-3 ***


[[-4.81285544]
 [-4.963746  ]
 [ 6.37297801]
 [ 7.85661824]]


----------

