In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

In [2]:
class IrisModel(object):

    def __init__(self, file_name, seperator=' '):
        self.data = pd.read_csv(u'data/{0}'.format(file_name), sep=seperator)

        feature1 = np.matrix(self.data.sl[0:]).T
        feature2 = np.matrix(self.data.sw[0:]).T
        feature3 = np.matrix(self.data.pl[0:]).T
        feature4 = np.matrix(self.data.pw[0:]).T

        self.X = np.hstack((feature1, feature2, feature3, feature4))
        self.w = np.matrix([1,1,1,1]).T

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def classify(self, category, iteration_count=10000, eta=0.001):
        y = np.matrix(self.data.c[0:]).T

        item_count = len(y)
        for i in range(item_count):
            y[i,0] = 1 if y[i,0] == category else 0

        for i in range(iteration_count):
            pr = self.sigmoid(self.X * self.w)
            self.w = self.w + eta * self.X.T * (y - pr)

        return self.w

In [14]:
model = IrisModel('iris.txt');

In [15]:
# Classify 1 versus 2,3
print(model.classify(1))

[[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]


In [16]:
# Classify 2 versus 1,3
print(model.classify(2))

[[ 0.73297827]
 [-1.87863923]
 [ 1.0469775 ]
 [-2.84360536]]


In [17]:
# Classify 3 versus 1,2
print(model.classify(3))

[[-4.88180307]
 [-4.9494954 ]
 [ 6.50105879]
 [ 7.71000705]]
