In [34]:
import numpy as np
import pandas as pd

## Read and prepare the data
df_iris = pd.read_csv(u'data/iris.txt',sep=' ')

sl = np.matrix(df_iris.sl).T
sw = np.matrix(df_iris.sw).T
pl = np.matrix(df_iris.pl).T
pw = np.matrix(df_iris.pw).T

X = np.hstack((sl,sw,pl,pw))

In [62]:
## Helper Functions
def sigmoid(x):
    return 1/(1+np.exp(-x))

def applyLogisticRegressionForClass(eta,iteration,X,currentClass):
    y = np.matrix(df_iris.c).T
    w = np.matrix([0,0,0,0]).T
    y[y != currentClass] = 0
    y[y == currentClass] = 1        
    
    for i in range(iteration):
        pr = sigmoid(X*w)
        w = w + eta*X.T*(y-pr) 
    return w;

In [63]:
print("Classifying class 1 against class 2 and class 3 \n")
w_class_1 = applyLogisticRegressionForClass(0.001,1000,X,1)
print(w_class_1)

Classifying class 1 against class 2 and class 3 

[[ 0.63211484]
 [ 2.0112702 ]
 [-3.09189333]
 [-1.4141242 ]]


In [69]:
print("Classifying class 2 against class 1 and class 3 \n")
w_class_2 = applyLogisticRegressionForClass(0.001,1000,X,2)
print(w_class_2)

Classifying class 2 against class 1 and class 3 

[[ 0.82124986]
 [-1.87564507]
 [ 0.60622843]
 [-1.87388846]]


In [67]:
print("Classifying class 3 against class 1 and class 2 \n")
w_class_3 = applyLogisticRegressionForClass(0.001,1000,X,3)
print(w_class_3)

Classifying class 3 against class 1 and class 2 

[[-2.62821246]
 [-2.33295249]
 [ 3.55016773]
 [ 3.47792202]]
