In [2]:
import numpy as np
import pandas as pd

data_items = pd.read_csv( "iris.txt", sep=" " )

In [11]:
# Sigmoid function definition

def sigmoid( t ):
    return 1 / (  1 + np.exp( -t ) )

In [20]:
values = np.hstack( 
        ( np.vstack( data_items.sl ),        
np.vstack( data_items.sw ),        
np.vstack( data_items.pl ),         
np.vstack( data_items.pw )
 ) )

In [21]:
y = np.vstack( data_items.c )

result = np.matrix( np.ones( 4 ) ).T

for i in range( len( y ) ):
    y[i,0] = 1 if y[i,0] == 1 else 0
    
for i in range( 10000 ):
    p = sigmoid( values * result )
    result = result + 0.001 * values.T * ( y - p )
print( result )

[[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]


In [23]:
y = np.vstack( data_items.c )

result = np.matrix( np.ones( 4 ) ).T

for i in range( len( y ) ):
    y[i,0] = 1 if y[i,0] == 2 else 0
    
for i in range( 10000 ):
    p = sigmoid( values * result )
    result = result + 0.001 * values.T * ( y - p )
print( result )

[[ 0.73300616]
 [-1.87866542]
 [ 1.04693053]
 [-2.84352623]]


In [34]:
y = np.vstack( data_items.c )

result = np.matrix( np.ones( 4 ) ).T

for i in range( len( y ) ):
    y[i,0] = 1 if y[i,0] == 3 else 0
    
for i in range( 10000 ):
    p = sigmoid( values * result )
    result = result + 0.001 * values.T * ( y - p )
print( result )

[[-4.80685745]
 [-4.96911165]
 [ 6.35877022]
 [ 7.88567013]]
