In [1]:
import numpy as np
import pandas as pd
from numpy import genfromtxt

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def classify(category, x, y):
   
    y_test = y.copy()
    w = np.matrix([1,1,1,1]).T
    eta = 0.001
    
    for i in range(len(y_test)):
        if (y_test[i,0] == category):
            y_test[i,0] = 1
        else:
            y_test[i,0] = 0
      
    for i in range(10000):
        pr = sigmoid(x*w)
        w = w + eta*x.T*(y_test-pr)

    return w

# 'skip_header' skips (1) row (which is the header) 
data_array = genfromtxt('data/iris.txt', delimiter=' ', usecols = (0,1,2,3), skip_header = 1)
category_array = genfromtxt('data/iris.txt', delimiter=' ', usecols = (4), skip_header = 1)

x = np.matrix(data_array)
y = np.matrix(category_array).T

print ("Classify 1 versus 2,3:")
w = classify(1, x, y)
print (w)

print ("Classify 2 versus 1,3:")
w = classify(2, x, y)
print (w)

print ("Classify 3 versus 1,2:")
w = classify(3, x, y)
print (w)

Classify 1 versus 2,3:
[[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]
Classify 2 versus 1,3:
[[ 0.73300616]
 [-1.87866542]
 [ 1.04693053]
 [-2.84352623]]
Classify 3 versus 1,2:
[[-4.80685745]
 [-4.96911165]
 [ 6.35877022]
 [ 7.88567013]]
