In [6]:
# Logistic Regression
# Using the Iris dataset, find the optimum logistic regression parameters for the following three problems:
# - Classify 1 versus 2,3
# - Classify 2 versus 1,3
# - Classify 3 versus 1,2
# Your program should output three parameter vectors, each of lenght 4

%matplotlib inline
from cvxpy import *
import numpy as np
import matplotlib as mpl
import matplotlib.pylab as plt
import pandas as pd

#load data from file
dfIrisAll = pd.read_csv(u'data/iris.txt',sep=' ')
dfIrisClass = dfIrisAll[['c']]
dfIrisAll = dfIrisAll[['sl','sw','pl','pw']]

#print(dfIrisAll.describe())

y1 = np.matrix(dfIrisClass.replace(2,0, regex=True).replace(3,0, regex=True))
y2 = np.matrix(dfIrisClass.replace(1,0, regex=True).replace(3,0, regex=True).replace(2,1, regex=True))
y3 = np.matrix(dfIrisClass.replace(1,0, regex=True).replace(2,0, regex=True).replace(3,1, regex=True))

N = dfIrisAll.shape[0]
#X = np.hstack((dfIrisAll, np.ones((N,1)) ))
X = np.matrix(dfIrisAll)
eta = 0.001

def sigmoid(x):
    return 1/(1+np.exp(-x))

def classify(y,description):
    w = np.matrix([1,1,1,1]).T
    
    for i in range(10000):
        pr = sigmoid(X*w)
        w = w + eta*X.T*(y-pr)
        
    print(description)
    print(w)
    print("\n")
    
# - Classify 1 versus 2,3
classify(y1,"Classify 1 versus 2,3")

# - Classify 2 versus 1,3
classify(y2,"Classify 2 versus 1,3")

# - Classify 3 versus 1,2
classify(y3,"Classify 3 versus 1,2")

Classify 1 versus 2,3
[[ 0.24393738]
 [ 3.96149207]
 [-4.37605233]
 [-1.83601484]]


Classify 2 versus 1,3
[[ 0.73248272]
 [-1.87817388]
 [ 1.04781246]
 [-2.84501201]]


Classify 3 versus 1,2
[[-4.83615723]
 [-4.95078113]
 [ 6.40550437]
 [ 7.82492124]]


