In [ ]:
SWE546_Assignment2
Logistic Regression

Using the Iris dataset, find the optimum logistic regression parameters for the following three problems:

Classify 1 versus 2,3
Classify 2 versus 1,3
Classify 3 versus 1,2
Your program should output three parameter vectors, each of lenght 4

Student Name : Zeyneb ESENDİR

In [51]:
%matplotlib inline

import scipy as sc
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import sys

fileName='data/iris.txt'
eta = 0.001

#read iris.txt and put values into irisData 
irisData = pd.read_csv(fileName,sep=' ')

#sigmoid func
def sigmoid(x):
    return 1/(1 + np.exp(-x))



#do all procedures are listed below for 1,2 and 3
for value in range(1,4):
    # original columns in txt file : sl sw pl pw c // create new matrix using the columns
    x = np.hstack((np.matrix(irisData.sl[0:]).T,np.matrix(irisData.sw[0:]).T,np.matrix(irisData.pl[0:]).T,np.matrix(irisData.pw[0:]).T))
    w = np.matrix([1,1,1,1]).T
    z= np.matrix(irisData.c[0:]).T
    
    for i in range(150):
            if z[i,0] == value:
                z[i,0] = 1
            else:
                z[i,0] = 0

    for i in range(10000):
        pr = sigmoid(x*w)
        w = w + eta*x.T*(z-pr) 

        
    if value==1:
        print("classify " , value," versus 2,3",'\n\n',w)
    if value==2:
        print('\n',"classify " , value," versus 1,3",'\n\n',w)
    if value==3:
        print('\n',"classify " , value," versus 1,2",'\n\n',w)


classify  1  versus 2,3 

 [[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]

 classify  2  versus 1,3 

 [[ 0.73300616]
 [-1.87866542]
 [ 1.04693053]
 [-2.84352623]]

 classify  3  versus 1,2 

 [[-4.80685745]
 [-4.96911165]
 [ 6.35877022]
 [ 7.88567013]]
