** BOUN SWE546 ASSIGNMENT 2 **

by Mahmut Ali ÖZKURAN.


### Loading Required Libraries With Data



In [55]:
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd
from scipy.special import expit as sigmoid

iris = datasets.load_iris()
iris_x = iris.data  # data
iris_y = iris.target  # classes
#print(iris_x[:,0])
#print(iris_x)
#print(iris_y)

### Classes

In [22]:
print(iris_y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Data

In [23]:
print(iris_x[:10])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]


### Classify

In [54]:
for x in range(0, 3):
    classes = np.matrix(iris_y).T
    vs = np.matrix([1,1,1,1]).T
    val = np.matrix(iris_x)

    for i in range(len(classes)):
        if classes[i,0] == x:
            classes[i,0] = 1
        else:
            classes[i,0] = 0
    #print(classes)
    print("Classifying class %d vs other two" % x)
    for i in range(10000):
        pr = sigmoid(iris_x*vs)
        vs = vs+0.0001*iris_x.T*(classes-pr)

    print(vs)

Classifying class 0 vs other two
[[ 0.3857123 ]
 [ 2.37658554]
 [-3.16898511]
 [-0.83440533]]
Classifying class 1 vs other two
[[ 0.82353294]
 [-1.86190427]
 [ 0.54807294]
 [-1.73390722]]
Classifying class 2 vs other two
[[-2.67684002]
 [-2.20809487]
 [ 3.45686165]
 [ 3.72025078]]
