# SWE 546 ASSIGNMENT2

Umur Türkay

In [264]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt

In [265]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

eta = 0.001

In [266]:
#the function reading the iris file and setting a c array
def readData(fileName):
    dataFrame = pd.read_csv(fileName,sep=' ')
    classArray = np.hstack(dataFrame.c.drop_duplicates())
    
    return(dataFrame, classArray)

#the function which does the classifying and prints the optimum logistic regression parameters (w) for the corresponding
#c value
def classify(dataFrame, classArray, cls):
    dataColumns = dataFrame[['sl','sw','pl','pw']]
    
    X = np.matrix(dataColumns)
    w = np.matrix([1,1,1,1]).T
    
    y = dataFrame[['c']]
    for i in range(len(classArray)):
        if classArray[i] == cls:
            y = y.replace(classArray[i],1)
        else:
            y = y.replace(classArray[i],0)
    
    y = np.matrix(y)
    for i in range(10000):
        prob = sigmoid(X*w)
        w = w + eta*X.T*(y-prob)
        
    print(w)    

In [267]:
dataFrame, classArray = readData('iris.txt')

In [268]:
#Classify 1 versus 2,3
classify(dataFrame, classArray, 1)

[[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]


In [269]:
#Classify 2 versus 1,3
classify(dataFrame, classArray, 2)

[[ 0.73300616]
 [-1.87866542]
 [ 1.04693053]
 [-2.84352623]]


In [270]:
#Classify 3 versus 1,2
classify(dataFrame, classArray, 3)

[[-4.80685745]
 [-4.96911165]
 [ 6.35877022]
 [ 7.88567013]]
