# NİHAL ER | 2015719069

SWE546 - Assignment2 || Logistic Regression

Using the Iris dataset, find the optimum logistic regression parameters for the following three problems:

1- Classify 1 versus 2,3

2- Classify 2 versus 1,3

3- Classify 3 versus 1,2

Your program should output three parameter vectors, each of lenght 4

In [45]:
%matplotlib inline
import numpy as np
import pandas as pd


df_iris = pd.read_csv(u'iris.txt',sep=' ')


#Define Sigmoid function

def sigmoid(x):
    return 1/(1+np.exp(-x))


#Define X,w,eta

#Column sl,sw,pl,pw will be the features of this model, in other words, these columns will create X matrix
X = np.hstack((np.matrix(df_iris.sl[0:]).T,np.matrix(df_iris.sw[0:]).T,np.matrix(df_iris.pl[0:]).T,np.matrix(df_iris.pw[0:]).T))
w = np.matrix([1,1,1,1]).T
eta = 0.001


**Problem1: Classify 1 versus 2,3**


In [46]:
y = np.matrix(df_iris.c[0:]).T

#if column c equals 1 then write 1, otherwise owerwrite with 0
for i in range(150):
        if y[i,0] == 1:
            y[i,0] = 1
        else:
            y[i,0] = 0
            
for i in range(10000):
    pr = sigmoid(X*w)
    w = w + eta*X.T*(y-pr) 

print(w)

[[ 0.71883956]
 [ 3.36466218]
 [-4.74062616]
 [-1.61263832]]


**Problem2: Classify 2 versus 1,3**


In [47]:
y = np.matrix(df_iris.c[0:]).T

#if column c equals 2 then write 1, otherwise owerwrite with 0
for i in range(150):
        if y[i,0] == 2:
            y[i,0] = 1
        else:
            y[i,0] = 0
            
for i in range(10000):
    pr = sigmoid(X*w)
    w = w + eta*X.T*(y-pr) 

print(w)

[[ 0.73297827]
 [-1.87863923]
 [ 1.0469775 ]
 [-2.84360536]]


**Problem3: Classify 3 versus 1,2**


In [48]:
y = np.matrix(df_iris.c[0:]).T

#if column c equals 3 then write 1, otherwise owerwrite with 0
for i in range(150):
        if y[i,0] == 3:
            y[i,0] = 1
        else:
            y[i,0] = 0
            
for i in range(10000):
    pr = sigmoid(X*w)
    w = w + eta*X.T*(y-pr) 

print(w)

[[-4.88180307]
 [-4.9494954 ]
 [ 6.50105879]
 [ 7.71000705]]
