In [7]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt


dataSetIris = pd.read_csv("../data/iris.txt",delim_whitespace=True)
#print dataSetIris
x = np.hstack((np.matrix(dataSetIris.sl[0:]).T, np.matrix(dataSetIris.sw[0:]).T, 
               np.matrix(dataSetIris.pl[0:]).T, np.matrix(dataSetIris.pw[0:]).T))
#print x
y = np.hstack(np.matrix(dataSetIris.c[0:]).T)
#print y
y1 = np.hstack(np.matrix(dataSetIris.c[0:]).T)
y2 = np.hstack(np.matrix(dataSetIris.c[0:]).T)
y3 = np.hstack(np.matrix(dataSetIris.c[0:]).T)

#y1 = y2 = y3 = y

for i in range(150):
    if y[0, i] == 1:
        y1[0, i] = 1
        y2[0, i] = 0
        y3[0, i] = 0
    elif y[0, i] == 2:
        y1[0, i] = 0
        y2[0, i] = 1
        y3[0, i] = 0
    elif y[0, i] == 3:
        y1[0, i] = 0
        y2[0, i] = 0
        y3[0, i] = 1
        
#print y
#print y1
#print y2
#print y3

def sigmoid(x):
    return 1/(1+np.exp(-x))

w = np.random.randn(4,1)
#np.mat('[1;2;3;4]')
w1 = np.random.randn(4,1)
w2 = np.random.randn(4,1)
w3 = np.random.randn(4,1)
#print w
        
#print(sigmoid(x*w))
eta = 0.001

for i in range(10000):
    pr1 = sigmoid(x*w1)
    w1 = w1 + eta*x.T*(y1.T-pr1)
    pr2 = sigmoid(x*w2)
    w2 = w2 + eta*x.T*(y2.T-pr2)
    pr3 = sigmoid(x*w3)
    w3 = w3 + eta*x.T*(y3.T-pr3)
    
    
print w1 # parameter vector for classification of 1 versus 2 and 3
#print(np.hstack((y1.T,pr1)))  
print w2 # parameter vector for classification of 2 versus 1 and 3
#print(np.hstack((y2.T,pr2)))  
print w3 # parameter vector for classification of 3 versus 1 and 2
#print(np.hstack((y3.T,pr3)))        
        
        
        
#print x

[[-0.61255398]
 [ 1.93839412]
 [-0.12614168]
 [-0.41629635]]
[[ 1.58995714]
 [ 2.20437927]
 [-4.96557779]
 [-2.45038125]]
[[ 0.73247355]
 [-1.87816528]
 [ 1.04782794]
 [-2.8450381 ]]
[[-4.86500391]
 [-4.93600418]
 [ 6.46527822]
 [ 7.72990499]]
